==8849== 232 bytes in 1 blocks are possibly lost in loss record 27,598 of 35,346
==8849==    at 0x483877F: malloc (vg_replace_malloc.c:309)
==8849==    by 0x226C82: _PyObject_GC_Alloc (gcmodule.c:1696)
==8849==    by 0x226C82: _PyObject_GC_Malloc (gcmodule.c:1718)
==8849==    by 0x226DFD: _PyObject_GC_New (gcmodule.c:1730)
==8849==    by 0x189B7D2E: ffi_internal_new (ffi_obj.c:40)
==8849==    by 0x189B7D2E: b_init_cffi_1_0_external_module (cffi1_module.c:197)
==8849==    by 0x2447C1: _PyMethodDef_RawFastCallDict (call.c:497)
==8849==    by 0x244AE0: _PyCFunction_FastCallDict (call.c:582)
==8849==    by 0x1B39EA: _PyObject_CallFunctionVa (call.c:957)
==8849==    by 0x2843B6: callmethod (call.c:1027)
==8849==    by 0x2843B6: PyObject_CallMethod (call.c:1046)
==8849==    by 0x18DF6F73: _cffi_init (py21cmfast.c_21cmfast.c:401)
==8849==    by 0x18E32D1B: PyInit_c_21cmfast (py21cmfast.c_21cmfast.c:2534)
==8849==    by 0x33A594: _PyImport_LoadDynamicModuleWithSpec (importdl.c:159)
==8849==    by 0x33A7A8: _imp_create_dynamic_impl.isra.15 (import.c:2158)
==8849==    by 0x33A7A8: _imp_create_dynamic (import.c.h:289)

==8849== 5,016 (16 direct, 5,000 indirect) bytes in 1 blocks are definitely lost in loss record 34,453 of 35,346
==8849==    at 0x483877F: malloc (vg_replace_malloc.c:309)
==8849==    by 0x19069C14: gsl_rng_alloc (in /usr/lib/libgsl.so.25.0.0)
==8849==    by 0x18E283C1: ComputeInitialConditions (GenerateICs.c:75)
==8849==    by 0x18E2F630: _cffi_f_ComputeInitialConditions (py21cmfast.c_21cmfast.c:1011)
==8849==    by 0x244BE6: cfunction_call_varargs (call.c:768)
==8849==    by 0x244BE6: PyCFunction_Call (call.c:784)
==8849==    by 0x2DE150: do_call_core (ceval.c:4641)
==8849==    by 0x2DE150: _PyEval_EvalFrameDefault (ceval.c:3191)
==8849==    by 0x21EDB8: _PyEval_EvalCodeWithName (ceval.c:3930)
==8849==    by 0x280A26: _PyFunction_FastCallKeywords (call.c:433)
==8849==    by 0x2D98FD: call_function (ceval.c:4616)
==8849==    by 0x2D98FD: _PyEval_EvalFrameDefault (ceval.c:3139)
==8849==    by 0x21EDB8: _PyEval_EvalCodeWithName (ceval.c:3930)
==8849==    by 0x280A26: _PyFunction_FastCallKeywords (call.c:433)
==8849==    by 0x2D98FD: call_function (ceval.c:4616)
==8849==    by 0x2D98FD: _PyEval_EvalFrameDefault (ceval.c:3139)

==8849== 57,376 bytes in 1 blocks are possibly lost in loss record 35,197 of 35,346
==8849==    at 0x483877F: malloc (vg_replace_malloc.c:309)
==8849==    by 0x98A1053: mkl_serv_allocate (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_core.so)
==8849==    by 0x119BF4EB: compute_bwd_task (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_avx2.so)
==8849==    by 0xE6348F0: ttl_parallel_syncable_dynamic_team (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_intel_thread.so)
==8849==    by 0x119C08F9: compute_r2c_3d_bwd (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_avx2.so)
==8849==    by 0x104D6977: DftiComputeBackward (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_intel_lp64.so)
==8849==    by 0x682E0CF: DftiComputeBackward (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_rt.so)
==8849==    by 0x6828BAD: fftwf_execute (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_rt.so)
==8849==    by 0x18E291FE: ComputeInitialConditions (GenerateICs.c:186)
==8849==    by 0x18E2F630: _cffi_f_ComputeInitialConditions (py21cmfast.c_21cmfast.c:1011)
==8849==    by 0x244BE6: cfunction_call_varargs (call.c:768)
==8849==    by 0x244BE6: PyCFunction_Call (call.c:784)
==8849==    by 0x2DE150: do_call_core (ceval.c:4641)
==8849==    by 0x2DE150: _PyEval_EvalFrameDefault (ceval.c:3191)

==8849== 324,128 bytes in 1 blocks are possibly lost in loss record 35,315 of 35,346
==8849==    at 0x483877F: malloc (vg_replace_malloc.c:309)
==8849==    by 0x98A1053: mkl_serv_allocate (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_core.so)
==8849==    by 0x119C08B4: compute_r2c_3d_bwd (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_avx2.so)
==8849==    by 0x104D6977: DftiComputeBackward (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_intel_lp64.so)
==8849==    by 0x682E0CF: DftiComputeBackward (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_rt.so)
==8849==    by 0x6828BAD: fftwf_execute (in /home/steven/miniconda3/envs/21CMMC/lib/libmkl_rt.so)
==8849==    by 0x18E291FE: ComputeInitialConditions (GenerateICs.c:186)
==8849==    by 0x18E2F630: _cffi_f_ComputeInitialConditions (py21cmfast.c_21cmfast.c:1011)
==8849==    by 0x244BE6: cfunction_call_varargs (call.c:768)
==8849==    by 0x244BE6: PyCFunction_Call (call.c:784)
==8849==    by 0x2DE150: do_call_core (ceval.c:4641)
==8849==    by 0x2DE150: _PyEval_EvalFrameDefault (ceval.c:3191)
==8849==    by 0x21EDB8: _PyEval_EvalCodeWithName (ceval.c:3930)
==8849==    by 0x280A26: _PyFunction_FastCallKeywords (call.c:433)

==8446== 104 bytes in 1 blocks are definitely lost in loss record 7,112 of 10,897
==8446==    at 0x483877F: malloc (vg_replace_malloc.c:309)
==8446==    by 0x20F203: PyMem_Malloc (obmalloc.c:553)
==8446==    by 0x189B7C95: _my_Py_InitModule (cffi1_module.c:144)
==8446==    by 0x189B7C95: b_init_cffi_1_0_external_module (cffi1_module.c:192)
==8446==    by 0x2447C1: _PyMethodDef_RawFastCallDict (call.c:497)
==8446==    by 0x244AE0: _PyCFunction_FastCallDict (call.c:582)
==8446==    by 0x1B39EA: _PyObject_CallFunctionVa (call.c:957)
==8446==    by 0x2843B6: callmethod (call.c:1027)
==8446==    by 0x2843B6: PyObject_CallMethod (call.c:1046)
==8446==    by 0x18DF6F73: _cffi_init (py21cmfast.c_21cmfast.c:401)
==8446==    by 0x18E32D1B: PyInit_c_21cmfast (py21cmfast.c_21cmfast.c:2534)
==8446==    by 0x33A594: _PyImport_LoadDynamicModuleWithSpec (importdl.c:159)
==8446==    by 0x33A7A8: _imp_create_dynamic_impl.isra.15 (import.c:2158)
==8446==    by 0x33A7A8: _imp_create_dynamic (import.c.h:289)
==8446==    by 0x2449E1: _PyMethodDef_RawFastCallDict (call.c:530)

==8446== 232 bytes in 1 blocks are definitely lost in loss record 8,885 of 10,897
==8446==    at 0x483877F: malloc (vg_replace_malloc.c:309)
==8446==    by 0x226C82: _PyObject_GC_Alloc (gcmodule.c:1696)
==8446==    by 0x226C82: _PyObject_GC_Malloc (gcmodule.c:1718)
==8446==    by 0x226DFD: _PyObject_GC_New (gcmodule.c:1730)
==8446==    by 0x189B7D2E: ffi_internal_new (ffi_obj.c:40)
==8446==    by 0x189B7D2E: b_init_cffi_1_0_external_module (cffi1_module.c:197)
==8446==    by 0x2447C1: _PyMethodDef_RawFastCallDict (call.c:497)
==8446==    by 0x244AE0: _PyCFunction_FastCallDict (call.c:582)
==8446==    by 0x1B39EA: _PyObject_CallFunctionVa (call.c:957)
==8446==    by 0x2843B6: callmethod (call.c:1027)
==8446==    by 0x2843B6: PyObject_CallMethod (call.c:1046)
==8446==    by 0x18DF6F73: _cffi_init (py21cmfast.c_21cmfast.c:401)
==8446==    by 0x18E32D1B: PyInit_c_21cmfast (py21cmfast.c_21cmfast.c:2534)
==8446==    by 0x33A594: _PyImport_LoadDynamicModuleWithSpec (importdl.c:159)
==8446==    by 0x33A7A8: _imp_create_dynamic_impl.isra.15 (import.c:2158)
==8446==    by 0x33A7A8: _imp_create_dynamic (import.c.h:289)

==8446== 5,016 (16 direct, 5,000 indirect) bytes in 1 blocks are definitely lost in loss record 10,814 of 10,897
==8446==    at 0x483877F: malloc (vg_replace_malloc.c:309)
==8446==    by 0x19069C14: ???
==8446==    by 0x18E283C1: ComputeInitialConditions (GenerateICs.c:75)
==8446==    by 0x18E2F630: _cffi_f_ComputeInitialConditions (py21cmfast.c_21cmfast.c:1011)
==8446==    by 0x244BE6: cfunction_call_varargs (call.c:768)
==8446==    by 0x244BE6: PyCFunction_Call (call.c:784)
==8446==    by 0x2DE150: do_call_core (ceval.c:4641)
==8446==    by 0x2DE150: _PyEval_EvalFrameDefault (ceval.c:3191)
==8446==    by 0x21EDB8: _PyEval_EvalCodeWithName (ceval.c:3930)
==8446==    by 0x280A26: _PyFunction_FastCallKeywords (call.c:433)
==8446==    by 0x2D98FD: call_function (ceval.c:4616)
==8446==    by 0x2D98FD: _PyEval_EvalFrameDefault (ceval.c:3139)
==8446==    by 0x21EDB8: _PyEval_EvalCodeWithName (ceval.c:3930)
==8446==    by 0x280A26: _PyFunction_FastCallKeywords (call.c:433)
==8446==    by 0x2D98FD: call_function (ceval.c:4616)
==8446==    by 0x2D98FD: _PyEval_EvalFrameDefault (ceval.c:3139)
